<a href="https://colab.research.google.com/github/Ashishchhipa/Othello_Small_Version/blob/main/Copy_of_Othello.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def flip2(x, new_i, new_j, dir):
  if new_i == 5 or new_i == -1 or new_j == 5 or new_j == -1:
    return x
  else:
    curr_i = new_i + dir[0]
    curr_j = new_j + dir[1]
    # Check if curr_i and curr_j are within bounds before accessing x
    if 0 <= curr_i < 4 and 0 <= curr_j < 4:
      if x[curr_i][curr_j] == 1:
        flip2(x, curr_i, curr_j, dir)
      if x[curr_i][curr_j] == -1:
        x[new_i][new_j] = -1
        return x
  return x

In [ ]:
def flip1(x, new_i, new_j, dir):
  if new_i == 5 or new_i == -1 or new_j == 5 or new_j == -1:
    return x
  else:
    curr_i = new_i + dir[0]
    curr_j = new_j + dir[1]
    # Check if curr_i and curr_j are within bounds before accessing x
    if 0 <= curr_i < 4 and 0 <= curr_j < 4:
      if x[curr_i][curr_j] == -1:
        flip1(x, curr_i, curr_j, dir)
      if x[curr_i][curr_j] == 1:
        x[new_i][new_j] = 1
        return x
  return x

In [ ]:
def current_board(x, i , j, n):
  p = n
  if p == 1:
    dirs = [[-1,0],[0,-1,],[1,0],[0,1],[1,1],[-1,-1],[-1,1],[1,-1]]
    for dir in dirs:
      new_i = i + dir[0]
      new_j = j + dir[1]
      # Check if new_i and new_j are within the bounds of the array
      if 0 <= new_i < 4 and 0 <= new_j < 4:
        if x[new_i][new_j] == 1:
          continue
        if x[new_i][new_j] == -1: # Fixed: Removed extra brackets
          x = flip1(x,new_i,new_j,dir)
  else:
    dirs = [[-1,0],[0,-1,],[1,0],[0,1],[1,1],[-1,-1],[-1,1],[1,-1]]
    for dir in dirs:
      new_i = i + dir[0]
      new_j = j + dir[1]
      # Check if new_i and new_j are within the bounds of the array
      if 0 <= new_i < 4 and 0 <= new_j < 4:
        if x[new_i][new_j] == -1:
          continue
        if x[new_i][new_j] == 1:  # Fixed: Removed extra brackets
          x = flip2(x,new_i,new_j,dir)
  return x

In [ ]:
def move1(x,open):
  Open = []
  for i in range(4):
    for j in range(4):
      if x[i][j] == 1:
        Open.append((i,j))
  return Open

In [ ]:
def move2(x,open):
  Open = []
  for i in range(4):
    for j in range(4):
      if x[i][j] == -1:
        Open.append((i,j))
  return Open

In [ ]:
def Possible_Moves(x,Moves,closed):
  Move = []
  for i in Moves:
    dirs = [[-1,0],[0,-1,],[1,0],[0,1]]
    for dir in dirs:
      p = i[0] + dir[0]
      q = i[1] + dir[1]
      if p >= 0 and p < 4 and q >= 0 and q < 4:
        if x[p][q] == 0 and (p,q) not in Move:
          Move.append((p,q))
  return Move

In [ ]:
def Game(open,closed,n,x):
  while open != []:
    if n == -1:
      print("Current_Board")
      print(x)
      Moves = move1(x,open)
      # print("Moves",Moves)
      moves = Possible_Moves(x,Moves,closed)
      print("Possible Moves =", moves)
      print("Black Turn")
      while True:  # Keep asking for input until a valid integer is provided
          i = input("Choose Your Moves ith index ")
          j = input("Choose Your Moves jth index ")
          if i.isdigit() and j.isdigit():  # Check if both inputs are digits
              break
          else:
              print("Invalid input. Please enter integers for i and j.")
      # Convert i and j to integers before using them as indices
      x[int(i)][int(j)] = -1  # Convert i and j to integers
      New_Board = current_board(x,int(i),int(j),n)
      closed.append((int(i),int(j))) # Convert i and j to integers

      open.remove((int(i),int(j))) # Convert i and j to integers
      x = New_Board
      n = 1
      Game(open,closed,n,x)
    elif n == 1:
      print("Current_Board")
      print(x)
      Moves = move2(x,open)
      # print("Moves",Moves)
      moves = Possible_Moves(x,Moves,closed)
      print("Possible Moves =", moves)
      print("White Turn")
      while True:  # Keep asking for input until a valid integer is provided
          i = input("Choose Your Moves ith index ")
          j = input("Choose Your Moves jth index ")
          if i.isdigit() and j.isdigit():  # Check if both inputs are digits
              break
          else:
              print("Invalid input. Please enter integers for i and j.")
      # Convert i and j to integers before using them as indices
      x[int(i)][int(j)] = 1
      New_Board = current_board(x,int(i),int(j),n)# Convert i and j to integers
      closed.append((int(i),int(j)))# Convert i and j to integers
      open.remove((int(i),int(j)))# Convert i and j to integers
      x = New_Board
      n = -1
      Game(open,closed,n,x)
  return x

In [ ]:
def start(x):
  open = []
  closed = []
  for i in range(4):
    for j in range(4):
      if x[i][j] == 0:
        open.append((i,j))
  for i in range(4):
    for j in range(4):
      if x[i][j] == 1 or x[i][j] == -1:
        closed.append((i,j))
  Start_Game = Game(open,closed,-1,x)
  return x

In [ ]:
import numpy as np
## Here white = 1 and Black = -1
x = np.zeros((4,4),dtype=np.int16)
x[1][1] = 1
x[2][2] = 1
x[1][2] = -1
x[2][1] = -1
Game = start(x)
print(x)
cnt1 = 0
cnt2 = 0
for i in range(4):
  for j in range(4):
    if x[i][j] == 1:
      cnt2 += 1
    elif x[i][j] == -1:
      cnt1 += 1
if cnt1 > cnt2:
  print("Black Wins")
  print("Count of white =", cnt2)
  print("Count of black =", cnt1)
elif cnt1 < cnt2:
  print("White Wins")
  print("Count of white =", cnt2)
  print("Count of white =", cnt1)
else:
  print("Draw",cnt1,cnt2)

Current_Board
[[ 0  0  0  0]
 [ 0  1 -1  0]
 [ 0 -1  1  0]
 [ 0  0  0  0]]
Possible Moves = [(0, 1), (1, 0), (3, 2), (2, 3)]
Black Turn
Choose Your Moves ith index 0
Choose Your Moves jth index 1
Current_Board
[[ 0 -1  0  0]
 [ 0 -1 -1  0]
 [ 0 -1  1  0]
 [ 0  0  0  0]]
Possible Moves = [(0, 0), (0, 2), (1, 0), (1, 3), (2, 0), (3, 1)]
White Turn
Choose Your Moves ith index 0
Choose Your Moves jth index 0
Current_Board
[[ 1 -1  0  0]
 [ 0  1 -1  0]
 [ 0 -1  1  0]
 [ 0  0  0  0]]
Possible Moves = [(1, 0), (3, 2), (2, 3)]
Black Turn
Choose Your Moves ith index 1
Choose Your Moves jth index 0
Current_Board
[[ 1 -1  0  0]
 [-1 -1 -1  0]
 [ 0 -1  1  0]
 [ 0  0  0  0]]
Possible Moves = [(0, 2), (2, 0), (1, 3), (3, 1)]
White Turn
Choose Your Moves ith index 0
Choose Your Moves jth index 2
Current_Board
[[ 1  1  1  0]
 [-1 -1  1  0]
 [ 0 -1  1  0]
 [ 0  0  0  0]]
Possible Moves = [(0, 3), (1, 3), (3, 2), (2, 3)]
Black Turn
Choose Your Moves ith index 1
Choose Your Moves jth index 3
Current_Boar